name: R2S-OpenWrt-Without-Docker

on:
  schedule:
    - cron: 5 9 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 获取最新代码
      uses: actions/checkout@master
      with:
        ref: master

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
      pwd
      /bin/bash ./scripts/01_init_env.sh
