name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # 定时器
#  schedule:
#    - cron: 10 09 * * *
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Init Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: /bin/bash ./scripts/01_init_env.sh

    - name: Clone Source
      run: /bin/bash ./scripts/02_clone_source.sh master-v19.07.1 rk3328

    - name: Patch Kernel
      run: /bin/bash ./scripts/03_patch_kernel_5.4.sh

    - name: Config Seed
      run: /bin/bash ./scripts/04_config_seed.sh

    - name: Prepare Package
      run: /bin/bash ./scripts/05_prepare_packages.sh


    - name: Build Plugins
      run: |
        echo "xxxxxxx"
        pwd
        ls
        /bin/bash ./plugins/add_openclash.sh
        /bin/bash ./plugins/add_passwall.sh
        git apply ./patch/enable_autocore.diff
        sed -i 's/@LINUX_5_4//' package/lean/luci-app-flowoffload/Makefile
      - name: Config Mods
        run: /bin/bash ./scripts/06_config_mods.sh